name: qt5-application
version: 1
summary: Qt5 Application Example
description: A simple text editor
grade: stable
confinement: strict

apps:
  qt5-application:
    command: desktop-launch application
    plugs: [unity7, home]

parts:
  application:
    source: src/
    plugin: qmake
    qt-version: qt5
    after: [desktop-qt5]
